f

diff --git a/.github/workflows/v1.yml b/.github/workflows/v1.yml
--- a/.github/workflows/v1.yml
+++ b/.github/workflows/v1.yml
@@ -12,62 +12,62 @@ on:
       - develop
 
 jobs:
-  frontend:
-    runs-on: ubuntu-latest
+  # frontend:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: v18.16.0
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: v18.16.0
       
-      - name: Get node version
-        id: node
-        run: |
-          echo "version=$(node -v)" >> $GITHUB_OUTPUT
+  #     - name: Get node version
+  #       id: node
+  #       run: |
+  #         echo "version=$(node -v)" >> $GITHUB_OUTPUT
 
-      - name: Create env files
-        run: |
-          echo "${{secrets.APP_ENV_TS}}" > ./app/src/environments/env.ts
-          echo "${{secrets.APP_ENV_PROD_TS}}" > ./app/src/environments/env.prod.ts
+  #     - name: Create env files
+  #       run: |
+  #         echo "${{secrets.APP_ENV_TS}}" > ./app/src/environments/env.ts
+  #         echo "${{secrets.APP_ENV_PROD_TS}}" > ./app/src/environments/env.prod.ts
 
-      - name: Check if env files exists
-        run: |
-          if [ ! -f ./app/src/environments/env.ts ]; then
-            echo "app.env not found!"
-            exit 1
-          fi
+  #     - name: Check if env files exists
+  #       run: |
+  #         if [ ! -f ./app/src/environments/env.ts ]; then
+  #           echo "app.env not found!"
+  #           exit 1
+  #         fi
 
-          if [ ! -f ./app/src/environments/env.prod.ts ]; then
-            echo "app.env.prod not found!"
-            exit 1
-          fi
+  #         if [ ! -f ./app/src/environments/env.prod.ts ]; then
+  #           echo "app.env.prod not found!"
+  #           exit 1
+  #         fi
 
-      - name: Get node_modules cache
-        uses: actions/cache@v3
-        id: node_modules
-        with:
-          path: |
-            **/node_modules
-          # Adding node version as cache key
-          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
+  #     - name: Get node_modules cache
+  #       uses: actions/cache@v3
+  #       id: node_modules
+  #       with:
+  #         path: |
+  #           **/node_modules
+  #         # Adding node version as cache key
+  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
 
 
-      - name: Install dependencies
-        if: steps.node_modules.outputs.cache-hit != 'true'
-        working-directory: ./app
-        run: yarn install --frozen-lockfile
+  #     - name: Install dependencies
+  #       if: steps.node_modules.outputs.cache-hit != 'true'
+  #       working-directory: ./app
+  #       run: yarn install --frozen-lockfile
 
-      - name: Lint Code
-        working-directory: ./app
-        run: yarn lint
+  #     - name: Lint Code
+  #       working-directory: ./app
+  #       run: yarn lint
 
-      - name: Build project
-        working-directory: ./app
-        run: yarn build
+  #     - name: Build project
+  #       working-directory: ./app
+  #       run: yarn build
     
     # add front unit tests
 
@@ -113,7 +113,7 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
           name: coverage-report
-          path: $GITHUB_WORKSPACE/api/coverage.xml
+          path: api/coverage.xml
 
       # - name: check docker name
       #   run: docker ps && docker exec e-mall_api_1 ls /coverage.xml
